const serviceProviderConst = [
  {
    id: 1,
    title: 'ALL',
    subOptions: ['ALL'],
  },
  {
    id: 2,
    title: 'AGIRCULTRE',
    subOptions: [
      'Farming Mechanization Guidlines',
      'Farming Mechanization Prices',
      'Farming Mechanization Subsidy Pattern',
    ],
  },
  {
    id: 3,
    title: 'BR MART',
    subOptions: ['BR MART POSTPAID', 'BR MART REACHARGEs'],
  },
  {
    id: 4,
    title: 'DOST',
    subOptions: ['DSTH_AUTH'],
  },

  {
    id: 5,
    title: 'ESD',
    subOptions: [
      'HyFi HotSpot Locator',
      'Meseva Application Status',
      'Meseva Locator',
      'Ration Shops',
      'Weather Informaton',
    ],
  },
  {
    id: 6,
    title: 'ESEVEA',
    subOptions: [
      'ACT',
      'AIRTEL LAND LINE',
      'AIRTEL POSTPAID',
      'BSNL LANDLINE & POASTPAID',
      'DMA',
      'Driving License Badge',
      'Driving license Test Fee',
      'Duplicate Driving License',
      'Duplicate Learner License',
      'Electricity',
      'Fresh Driving License Test Slot Bokking',
      'HATHWAY',
      'IDEA POSTPAID',
      'Learner License Retest',
      'Learner license Test Fee',
      'Lifetax Payment',
      'New Learner License Test Slot Booking',
      'OTHERS',
      'Other Services fee payment',
      'Property Tax Payment',
      'RAJ_SWAGRUHA',
      'RTA Quartaley tax',
      'Renewal of Drivers License',
      'TATA LANDLINE & POSTPAID',
      'TRAFIC_CHALLAN',
      'TSNPDCL',
      'TSPRREE',
      'TSSPDCL_NEW',
      'WATER',
    ],
  },
  {
    id: 7,
    title: 'EVENTS',
    subOptions: ['EVENTS'],
  },
  {
    id: 8,
    title: 'ICICI',
    subOptions: ['Loan & Credit Cards', 'Saving Accounts'],
  },

  {
    id: 9,
    title: 'ITRETURNS',
    subOptions: ['TAXTOWIN'],
  },

  {
    id: 10,
    title: 'MEESEVA',
    subOptions: [
      'Aadhar Slot Booking',
      'AagriCulture Income Certificate',
      'BONALU_OFFERING_SEVA',
      'Birt & Death Certification Corrections',
      'Birth Certificate & Death Certificate',
      'CDMA_BIRTH_NA',
      'CDMA_TEST_BIRTH',
      'Cast Certficate to Brahmnin Commuinity',
      'Certified Copy of Registration Document',
      'Child Name Inclusion',
      'Community Date of Birth Certificate',
      'Current Adangal / Phani',
      'EBC Certificate',
      'Encumbrance Certificate',
      'F Line Petition Status',
      'F.M.B Copy',
      'Family Membership Certficate',
      'Income Certificate',
      'Issue of cc by AD or DY. Tashildar',
      'LRDB',
      'Mutation & E-Pattadhar',
      'NPDCL Name Change',
      'NPDCL Repayment',
      'NPDCL_LOADCHANGE',
      'Non-Availability of Birth & Death Certificate',
      'OBC Certifiate',
      'ONLINE_POOJA',
      'OTHERS',
      'Occupation Rights Certificate for InamLands',
      'POLICE_NOC_RC',
      'Petrolum NOC',
      'ROR-IB',
      'Residence Certificate',
      'SMK Seva Service',
      'SSJ_PRASADAM_SEVA',
      'SSR_TALAMBRALU_SEVA',
      'Sree Gnana Saraswathi Devasthanam Ticket',
      'Sree Seetha Ramachandra Swamy Vari Deavasthanam & Sri Raja Rajeshwara S.D. Temple Seva Booking',
      'Sree Seetha Ramachandra Swamy Vari Deavasthanam Temple Room Booking',
      'Sree Seetha Ramachandra Swamy Vari Deavasthanam Temple Seeva Booking',
      'Sree Seetha Ramachandra Swamy Vari Deavasthanam Seva Ticket',
      'Sri Bhadrakali Deavasthanam, Warangal Seva Service',
      'Sri Gnana Saraswathi Devasthanam Room Booking',
      'Sri Gnana Saraswathi Temple Donation',
      'Sri Hanuman Deavasthanam, Kondagattu Seva Service',
      'Sri Karmanghat Hanuman Temple Donation',
      'Sri Lakshmi Narasimha Swami vari Devasthanam Room Booking',
      'Sri Lakshmi Narasimha Swami vari Devasthanam Room Seva Ticket',
      'Sri Lakshmi Narasimha Swami vary & Sri Raja Rajeshwara S.D. Temple Room Booking',
      'Sri Lakshmi Narasimha Swami vari Devasthanam, Dharmapuri Seva Service',
      'Sri Lakshmi Narasimha Swami vari Temple Room Booking',
      'Sri Lakshmi Narasimha Swami vari Temple Seva Booking',
      'Sri Lakshmi Narasimha Swami vari Temple Room Booking',
      'Sri Lakshmi Narasimha Swami vari Temple Seva Booking',
      'Sri Peddamma Thalli Deavasthanam, Hyderabad Seva Service',
      'Sri Raja Rajeswara S.D. Temple Room Booking',
      'Sri Raja Rajeswara S.D. Temple Seva Booking',
      'Sri Raja Rajeswara S.D. Temple Donation',
      'Sri Raja Rajeswari Temple Donation',
      'Sri Raja Rajeswari Temple Seva Ticket',
      'Sri Raja Rajeswara Temple Room Booking',
      'Sri Sita Ramachandra Swamy Temple Room Booking',
      'Sri Ujjaini Mahankali Temple Donation',
      'Sri Ujjaini Mahankali Temple Seva Booking',
      'Sri Yellama Pochamma Temple Donation',
      'Sri Yellama Pochamma Temple Seva Booking',
      'Temple Room Booking',
      'Temple Seva Booking',
      'YELLAMA_ANUAL_SEVA',
    ],
  },
  {
    id: 11,
    title: 'OTHERS',
    subOptions: [
      'Additional RTA Service Portal',
      'GHMC App',
      'RTA m-Wallet App',
      'T Wallet App',
      'Telangana State Portal',
      'Tourism Portal',
      'Traffic Challan Portal',
    ],
  },
  {
    id: 12,
    title: 'RTA FEST',
    subOptions: [
      'ADDRESS_CHANGE_RC',
      'Addition of class of vechicle to DL',
      'Change of Address in Driving License',
      'DUPLICATE_DL',
      'DUPLICATE_LL',
      'DUPLICATE_PERMIT',
      'HISTORY_DL',
      'Hazardous Certificate of DL',
      'ISSUE_OF_NOC_CC',
      'Issue of Badge Service',
      'Issue of New Permit',
      'NEW LL for Expired DL',
      'RENEWEL_OF_PERMIT',
      'RENEW_LL',
      'RTAFEST_TOW',
      'Renewal of DL',
      'SURRENDER_DL',
      'TEMP_SPEC_PERMIT',
    ],
  },

  {
    id: 13,
    title: 'STAMPS_DHARANI',
    subOptions: [
      'Deficit Amount',
      'Encumbrance Certificate',
      'Market Value Assistance',
      'Penalty',
      'Right to Information',
      'Sale of Stamps',
      'Single Search(CC) Certified Copy',
      'Special Power of Attestation',
    ],
  },

  {
    id: 14,
    title: 'STAMPS_IGRS',
    subOptions: [
      'Any Other Stamp Services',
      'Deficit Amount',
      'Encumbrance Certificate_stamps',
      'Firms',
      'Franking',
      'Hindu Marriage',
      'Market Value Assistance',
      'Penalty',
      'Private Attendance Fee',
      'Right to Information',
      'sales of Stamps',
      'Single Search Certified Copy_Stamps',
      'Socities',
      'Special Marriage',
      'Special POA',
    ],
  },

  {
    id: 15,
    title: 'TASK',
    subOptions: ['College Registration', 'Student Registration'],
  },

  {
    id: 16,
    title: 'TEMPLES',
    subOptions: ['GANESH_SEVA', 'GAN_DONATION'],
  },

  {
    id: 17,
    title: 'TSRTC',
    subOptions: ['Bus Routes Info'],
  },
];

export default serviceProviderConst;
