export const MSSQL_ALL_TRANSACTIONS = 'MSSQL_ALL_TRANSACTIONS';
export const MSSQL_CUMULATIVE_TRANSACTIONS = 'MSSQL_CUMULATIVE_TRANSACTIONS';
export const MYSQL_TOTAL_COUNTS = 'MYSQL_TOTAL_COUNTS';
export const MYSQL_MOBILE_USERS = 'MYSQL_MOBILE_USERS';
export const MYSQL_TRANS_PLATFORM = 'MYSQL_TRANS_PLATFORM';
export const MSSQL_USER_DEVICE_LIST = 'MSSQL_USER_DEVICE_LIST';
export const MSSQL_TOTAL_PGNAME_LIST = 'MSSQL_TOTAL_PGNAME_LIST';

export const MSSQL_DEPARTMENTWISE_TOTAL = 'MSSQL_DEPARTMENTWISE_TOTAL';
export const MSSQL_SUB_DEPARTMENTWISE_TOTAL = 'MSSQL_SUB_DEPARTMENTWISE_TOTAL';

export const MYSQL_YESTERDAY_SUCCESS = 'MYSQL_YESTERDAY_SUCCESS';
export const MSSQL_GOT_TRANS_TOTAL = 'MSSQL_GOT_TRANS_TOTAL';
export const MSSQL_PAYMENT_TRANS_TOTAL = 'MSSQL_PAYMENT_TRANS_TOTAL';
export const MSSQL_DIFF_FROM_GOT = 'MSSQL_DIFF_FROM_GOT';
export const MSSQL_DIFF_FROM_PAYMENT_TRANAS = 'MSSQL_DIFF_FROM_PAYMENT_TRANAS';
export const MYSQL_MONTHLY_COUNTS = 'MYSQL_MONTHLY_COUNTS';

export const MSSQL_YEARLY_DATA = 'MSSQL_YEARLY_DATA';
export const MYSQL_YEARLY_MONTHLY_TRANS = 'MYSQL_YEARLY_MONTHLY_TRANS';

export const MYSQL_LATEST_TRANSACTIONS = 'MYSQL_LATEST_TRANSACTIONS';
export const LOADING_ON = 'LOADING_ON';
export const LOADING_OFF = 'LOADING_OFF';
