export const ALL_REPORTS_FROM_SETTLEMETS = 'ALL_REPORTS_FROM_SETTLEMETS';
export const TABLES_ADDITION = 'TABLES_ADDITION';

export const LOADING_ON = 'LOADING_ON';
export const LOADING_OFF = 'LOADING_OFF';

export const IS_DATA_OFF = 'IS_DATA_OFF';

export const CLEAR_REPORT_STATE = 'CLEAR_REPORT_STATE';
